import Navbar from "@/components/Navbar";
import Head from "next/head";
import {LayoutProps} from "antd";
import {LayoutContainer} from "@/components/Layout/styles";

export default function Layout({ children }: LayoutProps) {
    return (
        <LayoutContainer>
            <Head>
                <title>HNI Companion App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.svg"/>
            </Head>
            <Navbar />
            <main>
                {children}
            </main>
        </LayoutContainer>
    )
}