import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Profile from "@/components/Profile";
import React from "react";
import {useUser} from "@auth0/nextjs-auth0/client";

export default function Home() {
    const {user} = useUser();

    return (
        <>
            <Head>
                <title>HNI Companion App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                {user ? <Profile /> : <div>Not logged in</div>}
                {!user && (
                    <div>
                        <a href="/api/auth/login">Login</a>
                        <br/>
                        <a href="register">Or Register</a>
                    </div>
                )}
                {user && (
                    <div>
                        <a href="/api/auth/logout">Logout</a>
                    </div>
                )}

            </main>
        </>
    )
}
